{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yubel.serviceAccountName" . }}
  labels:
    {{- include "yubel.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yubel.fullname" . }}-secrets
  labels:
    {{- include "yubel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretEnv | nindent 2 }}
{{- end }}
