apiVersion: v2
name: yubel
description: Cloud-native, multi-target DAST orchestrator (Job/CronJob)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/ggeorgeazevedo/yubel
sources:
  - https://github.com/ggeorgeazevedo/yubel
keywords: [dast, security, appsec, devsecops, kubernetes, scanner]
maintainers:
  - name: Yubel contributors
